### PR TITLE
Patient Data for APM-E

### PR DESCRIPTION
**Pull request by hmayenve**
# Related Tickets

- [SAR-318](https://jira.amida-tech.com/browse/SAR-318)

# How Things Worked (or Didn't) Before This PR

No data to test APM-E measure in CQL execution

# How Things Work Now (And How to Test)

Added 1 file in `data/patients/metabolic-antipsychotics/` for children and adolescents. Update `.env` to use `APME_HEDIS_MY2022-1.0.0` and run with `yarn localread`. Change data in either of the 2022 files.

### CODE REVIEW

**Comment by anthem123** [comment]
Only the exclusions showed up as true, is that on purpose?

**Comment by jmfadeley** [comment]
@hmayenve did you mean for the results to run against `APME_HEDIS_MY2022-1.0.0`? I got results back for IMAE, which is a little confusing. 

I will test assuming APME is what you meant.

**Comment by jmfadeley** [comment]
@anthem123 taking a look at the documentation (document D, page 313), all three exclusions can only occur based on the hospice rules ."The hospice exclusion is not required. Refer to Exclusions in the Guidelines for the Rules for Allowable Adjustments." Code below goes:

`define "Exclusions 1":
  Hospice."Hospice Intervention or Encounter"

define "Exclusions 2":
  "Exclusions 1"

define "Exclusions 3":
  "Exclusions 1"`
  
From what Mike and I have been gathering, I believe this is technically okay. Explained, the CQL will return both denominator and exclusion no matter what. But if the NCQA gives their consent to use an adjusted HEDIS measurement, we would apply the exclusion to the denominator after calculation, changing what is report but _not_ altering the scores. This is a question I posed to the NCQA and although they've elevated it, we're still waiting to hear back. 

So I believe what @hmayenve is done is perfectly fine. If we change or mind or feel otherwise, I think all we need to do is change the `Procedure.code` for id "73a447f7-c7cd-ee4b-e007-4f4524458f1c" so it's something than "170935008" (found in value set `private\APME_HEDIS_MY2022-1.0.0\valuesets\2.16.840.1.113883.3.464.1004.1762.json`, referenced in NCQA's Hospice library).

**Review by jmfadeley — APPROVED** [review]

**Comment by hmayenve** [comment]
@anthem123 and @jmfadeley the results for the data I created should all be true not just the exclusions. I’m gonna check tomorrow what I did wrong and fix it.

**Comment by jmfadeley** [comment]
@hmayenve well hold on... I ran it with APME and got...

image

With results of...
image

That's true denominators and numerators across the board. @anthem123 did you run it with IMAE or APME?

**Comment by anthem123** [comment]
I bet I ran with IMAE.

**Review by anthem123 — APPROVED** [review]
After checking against the correct CQL files I have gotten the expected output. Approved

**Pull request merged**
