### PR TITLE
Feature/change date ranges

### PR DESCRIPTION
**Pull request by TylerNoblett**
# Related Tickets

- [SAR-91](https://jira.amida-tech.com/browse/SAR-91)

# Other Repos' PR(s) Intended to Work With This PR

- LINK_TO_THE_PR or "None."

# How Things Worked (or Didn't) Before This PR

I noticed that our date ranges in the CQL files look like this:

@2018-12-31T00:00:00.0, @2019-12-31T00:00:00.0, but we 

1) want the year we're working with to be 2020, and

2) want to start at the very beginning of 2020, and end at the end, so the dates should look like @2020-01-01T00:00:00.0, @2020-12-31T23:59:59.999

Additionally, we'll need to modify all of the dates in the FHIR data so that 2019 becomes 2020 and 2018 becomes 2019

Finally, change MeasurementPeriod to "Measurement Period" in files that use that terminology
# How Things Work Now (And How to Test)

I modified the dates - to test, I just compared the output of the three CQL files, and then compared it to the output of the three CQL files with the date changes to make sure they were the same

# Readiness

1. [x] This PR passes all automated tests.
2. [x] This PR has no linting errors.
3. [x] This PR's changes to configuration files have been documented in all appropriate places (such as but not limited to README.md), if applicable.

### CODE REVIEW

**Review by hmayenve — APPROVED** [review]
LGTM! Great Job!

**Comment by hmayenve** [comment]
@TylerNoblett It would be good to resolve the merge conflicts before merging.

**Comment by TylerNoblett** [comment]
> @TylerNoblett It would be good to resolve the merge conflicts before merging.

whoops! will do

**Review by JamesbZhu — APPROVED** [review]
LGTM

**Pull request merged**
